import WGARP.Demand
import WGARP.GlobalAfriat
import Mathlib.Analysis.Convex.Quasiconvex
import Mathlib.Topology.Compactness.Compact

set_option autoImplicit false

/-!
# Justifiable preferences and their demand

For a family of utilities `u : I → Utility L`, weak justifiability means
that at least one component utility supports the comparison.  On a compact
index set this is the sign content of

`max i, (u i x - u i y) ≥ 0`.

The definitions below isolate exactly that sign content, which is all that
Lemma 6 uses.  The main structural result in this file proves the degenerate
branch of Lemma 6: if all component utilities generate the same demand at
every budget, justifiable demand is ordinary demand for any one component,
and every rationalized finite dataset therefore satisfies GARP.
-/

namespace WGARP

open Set

variable {L : ℕ} {I T : Type*}

/-- Weak preference in the justifiable model: some component utility
justifies the comparison. -/
def JustifiablyPreferred (u : I → Utility L) (x y : Bundle L) : Prop :=
  ∃ i, u i y ≤ u i x

/-- Strict preference induced by the justifiable weak relation. -/
def JustifiablyStrictlyPreferred
    (u : I → Utility L) (x y : Bundle L) : Prop :=
  JustifiablyPreferred u x y ∧ ¬ JustifiablyPreferred u y x

theorem not_justifiablyPreferred_iff
    (u : I → Utility L) (x y : Bundle L) :
    ¬ JustifiablyPreferred u x y ↔ ∀ i, u i x < u i y := by
  simp only [JustifiablyPreferred, not_exists, not_le]

/-- The strict part of a justifiable preference is unanimity: every
component utility must rank `x` strictly above `y`. -/
theorem justifiablyStrictlyPreferred_iff [Nonempty I]
    (u : I → Utility L) (x y : Bundle L) :
    JustifiablyStrictlyPreferred u x y ↔ ∀ i, u i y < u i x := by
  constructor
  · intro h
    exact (not_justifiablyPreferred_iff u y x).mp h.2
  · intro h
    let i₀ : I := Classical.choice inferInstance
    exact ⟨⟨i₀, (h i₀).le⟩,
      (not_justifiablyPreferred_iff u y x).mpr h⟩

/-- Every nonempty justifying family induces a complete weak relation. -/
theorem justifiablyPreferred_complete [Nonempty I]
    (u : I → Utility L) (x y : Bundle L) :
    JustifiablyPreferred u x y ∨ JustifiablyPreferred u y x := by
  let i₀ : I := Classical.choice inferInstance
  rcases le_total (u i₀ y) (u i₀ x) with h | h
  · exact Or.inl ⟨i₀, h⟩
  · exact Or.inr ⟨i₀, h⟩

/-- Demand generated by the justifiable preference relation. -/
def JustifiableDemand (u : I → Utility L)
    (p : Bundle L) (w : ℝ) (x : Bundle L) : Prop :=
  InBudget p w x ∧ ∀ y, InBudget p w y → JustifiablyPreferred u x y

/-- Dataset rationalization by the justifiable preference relation. -/
def JustifiableRationalizes {T : Type*}
    (D : Dataset L T) (u : I → Utility L) : Prop :=
  ∀ t y, Affordable D t y →
    JustifiablyPreferred u (D.choice t) y

/-- All component utilities induce the same demand correspondence. -/
def ComponentDemandsAgree (u : I → Utility L) : Prop :=
  ∀ i j p w x, UtilityDemand (u i) p w x ↔ UtilityDemand (u j) p w x

/-- A component utility maximizer is always a justifiable maximizer.  This
is the inclusion `⋃_u x_u(p,w) ⊆ x_r(p,w)` used in Lemma 6. -/
theorem utilityDemand_implies_justifiableDemand
    (u : I → Utility L) (i : I)
    (p : Bundle L) (w : ℝ) (x : Bundle L)
    (hx : UtilityDemand (u i) p w x) :
    JustifiableDemand u p w x := by
  refine ⟨hx.1, ?_⟩
  intro y hy
  exact ⟨i, hx.2 y hy⟩

/-! ## Compact budget sets and existence of utility demand -/

theorem inBudget_zero (p : Bundle L) {w : ℝ} (hw : 0 ≤ w) :
    InBudget p w 0 := by
  exact ⟨fun i ↦ le_rfl, by simpa using hw⟩

theorem inBudgetSet_nonempty (p : Bundle L) {w : ℝ} (hw : 0 ≤ w) :
    ({x : Bundle L | InBudget p w x}).Nonempty :=
  ⟨0, inBudget_zero p hw⟩

private theorem inBudgetSet_closed (p : Bundle L) (w : ℝ) :
    IsClosed {x : Bundle L | InBudget p w x} := by
  have hnonnegative : IsClosed {x : Bundle L | Nonnegative x} := by
    have heq :
        {x : Bundle L | Nonnegative x} =
          ⋂ i : Fin L, {x : Bundle L | x i ∈ Set.Ici 0} := by
      ext x
      simp only [Set.mem_setOf_eq, Set.mem_iInter, Set.mem_Ici, Nonnegative]
    rw [heq]
    exact isClosed_iInter fun i ↦ isClosed_Ici.preimage (continuous_apply i)
  have hcost : IsClosed {x : Bundle L | dot p x ≤ w} :=
    isClosed_Iic.preimage (continuous_dot p)
  simpa only [InBudget, setOf_and] using hnonnegative.inter hcost

/-- At strictly positive prices and nonnegative wealth, the budget set is
compact. -/
theorem inBudgetSet_compact
    (p : Bundle L) (w : ℝ) (hp : PositivePrice p) (hw : 0 ≤ w) :
    IsCompact {x : Bundle L | InBudget p w x} := by
  let box : Set (Bundle L) := Set.pi Set.univ (fun i ↦ Set.Icc 0 (w / p i))
  have hbox : IsCompact box := by
    exact isCompact_univ_pi fun _ ↦ isCompact_Icc
  have hsubset : {x : Bundle L | InBudget p w x} ⊆ box := by
    intro x hx
    rw [Set.mem_pi]
    intro i _hi
    refine ⟨hx.1 i, ?_⟩
    have hterm : p i * x i ≤ dot p x := by
      unfold dot
      exact Finset.single_le_sum
        (fun j _hj ↦ mul_nonneg (hp j).le (hx.1 j)) (Finset.mem_univ i)
    apply (le_div_iff₀ (hp i)).2
    calc
      x i * p i = p i * x i := by ring
      _ ≤ dot p x := hterm
      _ ≤ w := hx.2
  exact hbox.of_isClosed_subset (inBudgetSet_closed p w) hsubset

/-- A continuous utility attains a maximum on every nonempty positive-price
budget. -/
theorem exists_utilityDemand
    (u : Utility L) (p : Bundle L) (w : ℝ)
    (hu : Continuous u) (hp : PositivePrice p) (hw : 0 ≤ w) :
    ∃ x, UtilityDemand u p w x := by
  obtain ⟨x, hx, hmax⟩ :=
    (inBudgetSet_compact p w hp hw).exists_isMaxOn
      (inBudgetSet_nonempty p hw) hu.continuousOn
  exact ⟨x, hx, fun y hy ↦ hmax hy⟩

/-! ## The common-demand branch of Lemma 6 -/

/-- If all components have the same demand correspondence, justifiable
demand coincides with the demand of any selected component. -/
theorem justifiableDemand_iff_of_componentDemandsAgree
    [Nonempty I]
    (u : I → Utility L)
    (hcontinuous : ∀ i, Continuous (u i))
    (hagree : ComponentDemandsAgree u)
    (p : Bundle L) (w : ℝ) (hp : PositivePrice p) (hw : 0 ≤ w)
    (i₀ : I) (x : Bundle L) :
    JustifiableDemand u p w x ↔ UtilityDemand (u i₀) p w x := by
  constructor
  · intro hx
    obtain ⟨z, hz⟩ := exists_utilityDemand (u i₀) p w (hcontinuous i₀) hp hw
    refine ⟨hx.1, ?_⟩
    intro y hy
    by_contra hnot
    have hygt : u i₀ x < u i₀ y := lt_of_not_ge hnot
    have hx_not : ¬ UtilityDemand (u i₀) p w x := by
      intro hxd
      exact (not_lt_of_ge (hxd.2 y hy)) hygt
    have hz_all : ∀ i, UtilityDemand (u i) p w z := by
      intro i
      exact (hagree i₀ i p w z).mp hz
    have hx_not_all : ∀ i, ¬ UtilityDemand (u i) p w x := by
      intro i hxi
      exact hx_not ((hagree i i₀ p w x).mp hxi)
    have hstrict_all : ∀ i, u i x < u i z := by
      intro i
      have hle : u i x ≤ u i z := (hz_all i).2 x hx.1
      exact lt_of_le_of_ne hle fun heq ↦ by
        apply hx_not_all i
        refine ⟨hx.1, ?_⟩
        intro a ha
        calc
          u i a ≤ u i z := (hz_all i).2 a ha
          _ = u i x := heq.symm
    obtain ⟨i, hi⟩ := hx.2 z hz.1
    exact (not_lt_of_ge hi) (hstrict_all i)
  · exact utilityDemand_implies_justifiableDemand u i₀ p w x

/-- Under common component demand, every dataset rationalized by the
justifiable relation is rationalized by any selected component utility. -/
theorem utilityRationalizes_of_justifiable_of_componentDemandsAgree
    [Nonempty I] {T : Type*}
    (D : Dataset L T) (u : I → Utility L)
    (hcontinuous : ∀ i, Continuous (u i))
    (hagree : ComponentDemandsAgree u)
    (hrat : JustifiableRationalizes D u)
    (i₀ : I) :
    UtilityRationalizes D (u i₀) := by
  intro t y hy
  have hp : PositivePrice (D.price t) := D.price_pos t
  have hw : 0 ≤ expenditure D t (D.choice t) := by
    unfold expenditure dot
    exact Finset.sum_nonneg fun i _hi ↦
      mul_nonneg (D.price_pos t i).le (D.choice_nonneg t i)
  have hjust : JustifiableDemand u (D.price t)
      (expenditure D t (D.choice t)) (D.choice t) := by
    refine ⟨⟨D.choice_nonneg t, le_rfl⟩, ?_⟩
    intro z hz
    exact hrat t z hz
  have hordinary :=
    (justifiableDemand_iff_of_componentDemandsAgree
      u hcontinuous hagree (D.price t)
      (expenditure D t (D.choice t)) hp hw i₀ (D.choice t)).mp hjust
  exact hordinary.2 y hy

/-- The first alternative of Lemma 6: if all component demands agree, every
finite dataset rationalized by the justifiable model satisfies GARP. -/
theorem garp_of_justifiableRationalization_of_componentDemandsAgree
    [Nonempty I] [Fintype T] [Nonempty T]
    (D : Dataset L T) (u : I → Utility L)
    (hcontinuous : ∀ i, Continuous (u i))
    (hincreasing : ∀ i, StrictlyIncreasing (u i))
    (hagree : ComponentDemandsAgree u)
    (hrat : JustifiableRationalizes D u) :
    GARP D := by
  let i₀ : I := Classical.choice inferInstance
  exact garp_of_strictlyIncreasing_utilityRationalization D (u i₀)
    (hincreasing i₀)
    (utilityRationalizes_of_justifiable_of_componentDemandsAgree
      D u hcontinuous hagree hrat i₀)

end WGARP
